name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build solver.exe
      run: g++ -c -Wall -g solver.cpp -std=gnu++23
           g++ -g -o solver.exe solver.o -std=gnu++23
