name: Continuous Integration

on:
  push:
    branches: main
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    name: Build an executable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build solver.exe
        run: g++ -g -o solver.exe solver.cpp -std=gnu++23

  draft:
    name: Draft a release
    runs-on: ubuntu-latest
    steps:
      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            TODO before publishing:
             - mark if pre-release
             - add changelog
             - remove this
          draft: true
          files: solver.exe
