name: Continuous Integration

on:
  push:
    branches: main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build an executable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build solver.exe
        run: g++ -g -o solver.exe solver.cpp -std=gnu++23

  cd:
    name: Run CD
    needs: build
    uses: ./.github/workflows/CD.yml
