name: Continuous Integration/Continuous Deployment

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: write

jobs:
  build:
    name: Build an executable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build solver.exe
        run: g++ -g -o solver.exe solver.cpp -std=gnu++23
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./solver.exe
    
  draft:
    needs: build
    name: Draft a release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          
      - name: Create Draft Release
        uses: softprops/action-gh-release@v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            TODO before publishing:
             - mark if pre-release
             - add changelog
             - remove this
          draft: true
          files: ./solver.exe
